### ISSUE TITLE
Query strings not working on custom protocols (mock://)

### ISSUE THREAD

**Issue by kedare** [jamielennox/requests-mock#132]
Hello.

I started to use this library to mock API servers, it is working fine until when I start to have to match query strings, it looks like they get completely deleted during the process of going thru the matcher.

I made some tests and when I run real http requests, the value of `response.request.url` does include the query string (like `https://www.google.com/?test=true`), but when mocking, they are removed from the original URL (like `https://www.google.com/`)

Then it doesn't match the matchers (I get a `requests_mock.exceptions.NoMockAddress` when both the matcher and the query I an trying to run have the query strings)

I could not find any workaround so far, is this a known issue ?

```
requests==2.23.0
requests-mock==1.7.0
```

Thanks

**Comment by clslgrnc** [comment]
Do you have a minimal example?
I just tried and was unable to reproduce (from a fresh virtual environment with `requests==2.23.0̀` and `requests-mock==1.7.0`):
```python
Python 3.7.5 (default, Nov  7 2019, 10:50:52) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> from requests_mock import Mocker
>>> with Mocker() as m:
...   m.get("https://www.google.com/?test=true", text="success")
...   response = requests.get("https://www.google.com/?test=true")
...   print(response.text, response.request.url)
... 
<requests_mock.adapter._Matcher object at 0x7f101a97a550>
success https://www.google.com/?test=true
```

**Comment by kedare** [comment]
Looks like the issue is when using the params option:

``` python
import requests
import requests_mock

def build_session():
    session = requests.Session()
    adapter = requests_mock.Adapter()

    adapter.register_uri(
        "GET", "mock://example.com/?hello=world", text="""{"hello": "world"}"""
    )

    session.mount("mock", adapter)
    return session

def test_querystring():
    session = requests.Session()
    session.mount("mock", build_session())
    response = session.get("mock://example.com/", params={"hello": "world"})
    assert response.request.url == "mock://example.com/?hello=world"

def test_querystring2():
    with requests_mock.Mocker() as m:
        m.get("https://www.google.com/?test=true", text="success")
        response = requests.get("https://example.com/", params={"hello": "world"})
        assert response.request.url == "mock://example.com/?hello=world"
```

Both failing with :
`requests_mock.exceptions.NoMockAddress: No mock address: GET https://www.google.com/?hello=world`

**Comment by clslgrnc** [comment]
You're right.
I mainly use the Mocker object so I am not familiar with the adapter/mount approach. I slightly modifier your example since it seems you are mounting an adapter to a session then that session to another session. It sill does not work.
As for the Mocker approach it seems to be linked to the fake `mock` protocol, replacing with `http` or `https` solves the problem:
```python
import requests
import requests_mock
from uuid import uuid4


def build_adapter(protocol, text):
    adapter = requests_mock.Adapter()

    adapter.register_uri(
        "GET", f"{protocol}://example.com/?hello=world", text=text
    )

    return adapter


def test_querystring_adapter_mock():
    random_text = str(uuid4())
    session = requests.Session()
    session.mount("mock", build_adapter("mock", random_text))
    response = session.get("mock://example.com/", params={"hello": "world"})
    assert response.request.url == "mock://example.com/?hello=world"
    assert response.text == random_text


def test_querystring_mocker_mock():
    random_text = str(uuid4())
    with requests_mock.Mocker() as m:
        m.get("mock://example.com/?hello=world", text=random_text)
        response = requests.get("mock://example.com/", params={"hello": "world"})
        assert response.request.url == "mock://example.com/?hello=world"
        assert response.text == random_text


def test_querystring_adapter_http():
    random_text = str(uuid4())
    session = requests.Session()
    session.mount("http", build_adapter("http", random_text))
    response = session.get("http://example.com/", params={"hello": "world"})
    assert response.request.url == "http://example.com/?hello=world"
    assert response.text == random_text


def test_querystring_mocker_http():
    random_text = str(uuid4())
    with requests_mock.Mocker() as m:
        m.get("http://example.com/?hello=world", text=random_text)
        response = requests.get("http://example.com/", params={"hello": "world"})
        assert response.request.url == "http://example.com/?hello=world"
        assert response.text == random_text
```
```console
======================================== short test summary info ========================================
FAILED test.py::test_querystring_adapter_mock - requests_mock.exceptions.NoMockAddress: No mock addres...
FAILED test.py::test_querystring_mocker_mock - requests_mock.exceptions.NoMockAddress: No mock address...
FAILED test.py::test_querystring_adapter_http - assert '<!doctype ht...y>\n</html>\n' == '2cc43e0e-28a...
====================================== 3 failed, 1 passed in 0.26s ======================================
```

**Comment by kedare** [comment]
I fixed my `test_querystring` that was wrong (It could not work in the previous version) and still giving the same issue indeed.

Is this expected that we cannot use mock:// protocol ?

**Comment by clslgrnc** [comment]
It works when passing the arguments with the url instead of params, so I guess it should work.

**Comment by kedare** [comment]
Using params is afaik the recommended way to sent query string in requests, they should not be sent in the URL directly.

In my case I cannot change this behaviour because I just send the Session object to underlying objects that handle the requests

**Comment by clslgrnc** [comment]
As a temporary workaround, if you do not need exotic prefixes, and if mocking requests globally is not a problem, you might use the Mocker, mock everything you need, then create your Session object and send it to underlying objects:
```python
with requests_mock.Mocker() as m:
    m.get(...)
    session = requests.Session()
    my_obj = MyObj(session)
```

**Comment by clslgrnc** [comment]
It does not solve the problem with `mock`, but one explanation for why `http` works with Mocker and not mount/adapter is that Mocker completely replace the get_adapter function, ensuring that the mocked adapter is used, while mount only register a new adapter.

But adapters are sorted by decreasing length, and by defaults there are already two: `http://` and `https://`, thus when get_adapters is called:
https://github.com/psf/requests/blob/bfb93d4b7d269a8735f1b216093e7e9a9fdc4517/requests/sessions.py#L716-L728
The adapter for `http://` is returned, not the one for `http`.

In my previous comment, in `test_querystring_adapter_http`, replacing
```python
    session.mount("http", build_adapter("http", random_text))
```
with
```python
    session.mount("http://", build_adapter("http", random_text))
```
solves the problem.

The doc should probably be updated to emphasize that. But with the incoming ability to use Mocker with sessions the doc should probably drop the mount adapter approach (or at least says that it is for those who understand requests internals)

**Comment by clslgrnc** [comment]
As for `mock`, the culprit is here:
https://github.com/psf/requests/blob/bfb93d4b7d269a8735f1b216093e7e9a9fdc4517/requests/models.py#L371-L376
Requests does not perform URL preparation for non-HTTP schemes.

An http scheme starts with "http" and respect this regex:
```
SCHEME_RE = re.compile(r"^(?:[a-zA-Z][a-zA-Z0-9+-]*:|/)")
```
https://github.com/urllib3/urllib3/blob/263da24d4b5c33392772e638b12d02e5b07abf9f/src/urllib3/util/url.py#L18

Thus replacing `mock` with `http-mock://` as an example, solves the issue.

@kedare can you confirm that either solution solves the problem for you:
- a mount on "http://" (https://github.com/jamielennox/requests-mock/issues/132#issuecomment-612041147)
- a mount on "http-mock://"
- or through the Mocker (https://github.com/jamielennox/requests-mock/issues/132#issuecomment-611713649)

@jamielennox should I update the doc to warn that the protocol should start with http to ensure url preparation and that adapter mounted on http or https are ignored and should be mounted on http:// and https:// respectively.

**Comment by kedare** [comment]
I should be able to use https or http-mock instead of mock without issues.
Also I am also already providing the custom session object to my abstraction layer.
I will take a try next week to fake http.

I am basically building a client like this :

```
def build_session():
    session = requests.Session()
    adapter = requests_mock.Adapter()

    adapter.register_uri(
        "GET", "mock://example.com/?hello=world", text="""{"hello": "world"}"""
    )

    session.mount("mock", adapter)
    return session

client = APIClient(session_provider=build_session())
```

**Comment by clslgrnc** [comment]
With the updated doc, this can probably be closed.

**Comment by jamielennox** [comment]
Thanks for the help @clslgrnc
